application: fundrafrica
version: 1
runtime: php
api_version: 1

handlers:
- url: /
  script: index.php

- url: /create
  script: create.php

- url: /discover
  script: discover.php

- url: /learn
  script: learn.php

- url: /privacy
  script: privacy.php

- url: /terms
  script: terms.php

- url: /stylesheets
  static_dir: stylesheets
